### ISSUE TITLE
Crashing Android

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [ideacreation/react-native-barcodescanner#34]
Hi, sometimes while navigating my app I have this error

```
06-30 23:28:03.851  3036  3036 E CameraPreview: java.lang.RuntimeException: Camera is being used after Camera.release() was called
06-30 23:28:03.851  3036  3036 E CameraPreview: java.lang.RuntimeException: Camera is being used after Camera.release() was called
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.hardware.Camera.native_cancelAutoFocus(Native Method)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.hardware.Camera.cancelAutoFocus(Camera.java:1275)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.eguma.barcodescanner.CameraPreview.stopCameraPreview(CameraPreview.java:89)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.eguma.barcodescanner.CameraPreview.stopCamera(CameraPreview.java:52)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.eguma.barcodescanner.BarcodeScannerView.stopCamera(BarcodeScannerView.java:55)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.eguma.barcodescanner.BarcodeScannerManager.onHostDestroy(BarcodeScannerManager.java:63)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:182)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.facebook.react.ReactInstanceManagerImpl.moveToBeforeCreateLifecycleState(ReactInstanceManagerImpl.java:599)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.facebook.react.ReactInstanceManagerImpl.destroy(ReactInstanceManagerImpl.java:552)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:177)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.app.Activity.performDestroy(Activity.java:6407)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.app.ActivityThread.-wrap5(ActivityThread.java)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.os.Looper.loop(Looper.java:148)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at java.lang.reflect.Method.invoke(Native Method)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-30 23:28:03.851  3036  3036 E CameraPreview:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-30 23:28:04.001   833   861 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.activityDestroyed(android.os.IBinder) from ActivityManagerService.java:6475 waiters=0 for 110ms

```

Are there any actions I must take in order to prevent this ?

**Comment by andreaskeller** [comment]
@rafaelcorreiapoli I close this for now. You can reopen it if the error still occurs on the newest version.
