### ISSUE TITLE
Can't run Examples/BarcodeScanner: "undefined is not a function"

### ISSUE THREAD

**Issue by iivvoo** [ideacreation/react-native-barcodescanner#63]
The BarcodeScanner example does not work for me - not in an AVM or on an actual device. In both cases I get an error similar to

```
java.util.concurrent.ExecutionException
java.lang.RuntimeException:
TypeError: undefined is not a function
(evaluating '(bridgeConfig.remoteModuleConfig||[]).forEach')
...
createReactContext
ReactInstanceManagerImpl.java:911
access$700
ReactInstanceManagerImpl.java:100
...

```
(error typed not copied, may contain typo's)

I'm currently evaluating react-native as a platform for a simple app with qr code scanning functionality so I know very little about how to further debug this.

**Comment by iivvoo** [comment]
Turns out I ran "react-native start" from the wrong (different) project. The error is as cryptic as you'd expect from a JS code base :)

**Comment by vartika1403** [comment]
Got JS Exception: TypeError: undefined is not a function (evaluating '(bridgeConfig.remoteModuleConfig||[]).forEach')
02-24 16:30:45.632 21222-21251/com.awesomeproject E/unknown:React: Exception in native call from JS
                                                                   com.facebook.react.bridge.JSExecutionException: TypeError: undefined is not a function (evaluating '(bridgeConfig.remoteModuleConfig||[]).forEach') (line 3980 in the generated bundle)
                                                                       at com.facebook.react.bridge.ReactBridge.loadScriptFromFile(Native Method)
                                                                       at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:58)
                                                                       at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:154)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by vartika1403** [comment]
please can someone help me with this error

**Comment by phamios** [comment]
i got the same this error, pls help
